// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.2.0
// Project name: Interocitor

#ifndef _INTEROCITOR_UI_H
#define _INTEROCITOR_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Frame;
extern lv_obj_t * ui_Pause;
extern lv_obj_t * ui_Play;
extern lv_obj_t * ui_SongSelect;
extern lv_obj_t * ui_IPLable;
extern lv_obj_t * ui_IPValue;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_teslabackground_png);    // assets\TeslaBackground.png
LV_IMG_DECLARE(ui_img_interocitor_frame_png);    // assets\Interocitor_Frame.png
LV_IMG_DECLARE(ui_img_interocitor_pause_button_png);    // assets\Interocitor_Pause_Button.png
LV_IMG_DECLARE(ui_img_interocitor_play_button_png);    // assets\Interocitor_Play_Button.png

LV_FONT_DECLARE(ui_font_Digitaled);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
